### ISSUE TITLE
Support for annotations/labels

### ISSUE THREAD

**Issue by bigs** [ipfs/go-metrics-interface#3]
In my testbed work, I have a desire to tag metrics with metadata, which prometheus seems to support via [Labels](https://godoc.org/github.com/prometheus/client_golang/prometheus#Labels). Do we have any interest in adding basic string->string maps of metadata to these top level interfaces? I'd be happy to PR if we're interested, otherwise I'll use prometheus directly.

**Comment by Kubuxu** [comment]
As I think libp2p is standardising on OpenCensus, we also might go this path rendering this interface obsolete.
